name: merchant_evc_plus
description: Hormuud EvcPlus Merchant API Plugin
version: 0.0.2
homepage: https://github.com/baabale/merchant_evc_plus

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
